service: serverless-offline

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: GET

plugins:
  - serverless-webpack
  - serverless-offline